language: node_js
sudo: required
dist: trusty
after_success:
    - npm run travis-coveralls
node_js:
    - "10"
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
    packages:
        - g++-4.8
